dofile_once("mods/more_giga_spells/files/giga_energy_sphere/spell.lua")
dofile_once("mods/more_giga_spells/files/giga_spark_bolt/spell.lua")
dofile_once("mods/more_giga_spells/files/giga_spitter_bolt/spell.lua")
dofile_once("mods/more_giga_spells/files/giga_healing_bolt/spell.lua")
dofile_once("mods/more_giga_spells/files/giga_bouncing_burst/spell.lua")